# Generated by Django 4.1 on 2022-10-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='desc_fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta', models.CharField(max_length=500)),
                ('kilos_fruta', models.IntegerField(default=1)),
                ('medida_fruta', models.IntegerField(choices=[('K', 'Kilo(s)'), ('T', 'Tonelada(s)'), ('ND', 'No definido')], default=1)),
                ('valor_producto', models.IntegerField()),
                ('productor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='estado_productor_crear_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_venta', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='estado_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado_solicitud', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='estado_subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_subasta', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='estado_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_venta', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='frutas_espacio1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta_espacio1', models.CharField(max_length=120)),
                ('fk_desc_fruta_espacio1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desc_fruta')),
            ],
        ),
        migrations.CreateModel(
            name='frutas_espacio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta_espacio2', models.CharField(max_length=120)),
                ('fk_desc_fruta_espacio2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desc_fruta')),
            ],
        ),
        migrations.CreateModel(
            name='frutas_espacio3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta_espacio3', models.CharField(max_length=120)),
                ('fk_desc_fruta_espacio3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desc_fruta')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje_registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('apellido', models.CharField(max_length=1000)),
                ('email_mensaje', models.EmailField(max_length=254)),
                ('rut_personal', models.CharField(max_length=10)),
                ('movil_personal', models.CharField(max_length=11)),
                ('pais_personal', django_countries.fields.CountryField(max_length=2)),
                ('cuidad_personal', models.CharField(max_length=100)),
                ('direccion_personal', models.CharField(max_length=50)),
                ('profesion_personal', models.CharField(max_length=100)),
                ('sexo_personal', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OT', 'Otro')], max_length=500)),
                ('mensaje', models.TextField(max_length=5000)),
                ('tipo_personal_fk', models.CharField(choices=[('Administrador', 'Administrador'), ('Productor', 'Productor'), ('Cliente externo', 'Cliente externo'), ('Cliente interno', 'Cliente interno'), ('Transportista', 'Transportista'), ('Consultor', 'Consultor')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_perfil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_personal', models.CharField(max_length=10)),
                ('movil_personal', models.CharField(max_length=11)),
                ('pais_personal', django_countries.fields.CountryField(max_length=2)),
                ('cuidad_personal', models.CharField(max_length=100)),
                ('direccion_personal', models.CharField(max_length=50)),
                ('profesion_personal', models.CharField(max_length=100)),
                ('sexo_personal', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OT', 'Otro')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='producto_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='productor_crear_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_estado_productor_crear_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado_productor_crear_solicitud')),
                ('fk_frutas_espacio1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio1')),
                ('fk_frutas_espacio2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio2')),
                ('fk_frutas_espacio3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio3')),
            ],
        ),
        migrations.CreateModel(
            name='subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mi_apuesta', models.IntegerField()),
                ('fec_subasta', models.DateField(auto_now=True)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('cuidad', models.CharField(max_length=120)),
                ('mi_direccion', models.CharField(max_length=120)),
                ('fk_estado_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado_subasta')),
                ('fk_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productor_crear_solicitud')),
                ('fk_transportistaa_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tipo_empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_venta', models.DateField(auto_now=True)),
                ('fk_estado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado_venta')),
                ('fk_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subasta')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(max_length=100)),
                ('movil_usuario', models.CharField(max_length=100)),
                ('Perfil_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil_usuario')),
                ('Tipo_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario')),
                ('personal_id_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.personal')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta_espacio1', models.CharField(max_length=500)),
                ('kilos_fruta_espacio1', models.IntegerField(default=1)),
                ('nombre_fruta_espacio2', models.CharField(max_length=500)),
                ('kilos_fruta_espacio2', models.IntegerField(default=1)),
                ('nombre_fruta_espacio3', models.CharField(max_length=500)),
                ('kilos_fruta_espacio3', models.IntegerField(default=1)),
                ('fk_estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado_solicitud')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productor_crear_solicitud',
            name='fk_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solicitud'),
        ),
        migrations.AddField(
            model_name='productor_crear_solicitud',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_producto', models.CharField(max_length=30)),
                ('estado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_estado')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desc_fruta')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('create_record', 'Create product'),),
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_personal_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='mensaje_boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=5000)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social_cliente', models.CharField(max_length=100)),
                ('giro_cliente', models.CharField(max_length=180)),
                ('replegal_cliente', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=10)),
                ('tipo_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_boleta', models.DateField(auto_now=True)),
                ('valor_transporte', models.IntegerField()),
                ('valor_productos', models.IntegerField()),
                ('valor_total', models.IntegerField()),
                ('fk_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
