# Generated by Django 4.1 on 2022-11-03 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleta',
            options={'verbose_name': 'Boleta', 'verbose_name_plural': 'Boleta'},
        ),
        migrations.AlterModelOptions(
            name='desc_fruta',
            options={'verbose_name': 'Descripcion producto', 'verbose_name_plural': 'Descripcion producto'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AlterModelOptions(
            name='estado_productor_crear_solicitud',
            options={'verbose_name': 'Estado productor crear solicitud', 'verbose_name_plural': 'Estado productor crear solicitud'},
        ),
        migrations.AlterModelOptions(
            name='estado_solicitud',
            options={'verbose_name': 'Estado solicitud', 'verbose_name_plural': 'Estado solicitud'},
        ),
        migrations.AlterModelOptions(
            name='estado_subasta',
            options={'verbose_name': 'Estado subasta', 'verbose_name_plural': 'Estado subasta'},
        ),
        migrations.AlterModelOptions(
            name='estado_venta',
            options={'verbose_name': 'Estado de venta', 'verbose_name_plural': 'Estado de venta'},
        ),
        migrations.AlterModelOptions(
            name='frutas_espacio1',
            options={'verbose_name': 'Producto 1', 'verbose_name_plural': 'Producto 1'},
        ),
        migrations.AlterModelOptions(
            name='frutas_espacio2',
            options={'verbose_name': 'Producto 2', 'verbose_name_plural': 'Producto 2'},
        ),
        migrations.AlterModelOptions(
            name='frutas_espacio3',
            options={'verbose_name': 'Producto 3', 'verbose_name_plural': 'Producto 3'},
        ),
        migrations.AlterModelOptions(
            name='mensaje_boleta',
            options={'verbose_name': 'Mensaje boleta', 'verbose_name_plural': 'Mensaje boleta'},
        ),
        migrations.AlterModelOptions(
            name='mensaje_registro',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registro'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Pais'},
        ),
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={'verbose_name': 'Perfil usuario', 'verbose_name_plural': 'Perfil usuario'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('create_record', 'Create product'),), 'verbose_name': 'Producto', 'verbose_name_plural': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto_estado',
            options={'verbose_name': 'Producto estado', 'verbose_name_plural': 'Producto estado'},
        ),
        migrations.AlterModelOptions(
            name='productor_crear_solicitud',
            options={'verbose_name': 'Productor crear solicitud', 'verbose_name_plural': 'Productor crear solicitud'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitud'},
        ),
        migrations.AlterModelOptions(
            name='subasta',
            options={'verbose_name': 'Subasta', 'verbose_name_plural': 'Subasta'},
        ),
        migrations.AlterModelOptions(
            name='tipo_empresa',
            options={'verbose_name': 'Tipo de empresa', 'verbose_name_plural': 'Tipo de empresa'},
        ),
        migrations.AlterModelOptions(
            name='tipo_personal',
            options={'verbose_name': 'Rol personal', 'verbose_name_plural': 'Rol personal'},
        ),
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name': 'Rol usuario', 'verbose_name_plural': 'Rol usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuario'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Venta'},
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fec_boleta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de boleta'),
        ),
        migrations.AlterField(
            model_name='desc_fruta',
            name='kilos_fruta',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='desc_fruta',
            name='medida_fruta',
            field=models.IntegerField(choices=[('K', 'Kilo(s)'), ('T', 'Tonelada(s)'), ('ND', 'No definido')], default=1, verbose_name='Tipo de medida'),
        ),
        migrations.AlterField(
            model_name='desc_fruta',
            name='nombre_fruta',
            field=models.CharField(max_length=500, verbose_name='Nombre producto'),
        ),
        migrations.AlterField(
            model_name='desc_fruta',
            name='productor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='desc_fruta',
            name='valor_producto',
            field=models.IntegerField(verbose_name='Valor producto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro_cliente',
            field=models.CharField(max_length=180, verbose_name='Giro de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social_cliente',
            field=models.CharField(max_length=100, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='replegal_cliente',
            field=models.CharField(max_length=50, verbose_name='Representante legal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut_empresa',
            field=models.CharField(max_length=10, verbose_name='Rut de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_empresa', verbose_name='Tipo de empresa'),
        ),
        migrations.AlterField(
            model_name='estado_solicitud',
            name='desc_estado_solicitud',
            field=models.CharField(max_length=120, verbose_name='Estado de solicitud'),
        ),
        migrations.AlterField(
            model_name='estado_venta',
            name='estado_venta',
            field=models.CharField(max_length=120, verbose_name='Estado de venta'),
        ),
        migrations.AlterField(
            model_name='frutas_espacio1',
            name='nombre_fruta_espacio1',
            field=models.CharField(max_length=120, verbose_name='Nombre producto (1)'),
        ),
        migrations.AlterField(
            model_name='frutas_espacio2',
            name='nombre_fruta_espacio2',
            field=models.CharField(max_length=120, verbose_name='Nombre producto (2)'),
        ),
        migrations.AlterField(
            model_name='frutas_espacio3',
            name='nombre_fruta_espacio3',
            field=models.CharField(max_length=120, verbose_name='Nombre producto (3)'),
        ),
        migrations.AlterField(
            model_name='mensaje_boleta',
            name='mensaje',
            field=models.TextField(max_length=5000, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje_registro',
            name='tipo_personal_fk',
            field=models.CharField(choices=[('Productor', 'Productor'), ('Cliente externo', 'Cliente externo'), ('Cliente interno', 'Cliente interno'), ('Transportista', 'Transportista'), ('Consultor', 'Consultor'), ('Administrador', 'Administrador')], max_length=500),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Nombre pais'),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='desc_perfil',
            field=models.CharField(max_length=30, verbose_name='Descripcion de perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cuidad_personal',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='direccion_personal',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='movil_personal',
            field=models.CharField(max_length=11, verbose_name='Movil'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='pais_personal',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Seleccionar pais'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profesion_personal',
            field=models.CharField(max_length=100, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='rut_personal',
            field=models.CharField(max_length=10, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sexo_personal',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OT', 'Otro')], max_length=500, verbose_name='Seleccionar genero'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tipo_personal_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_personal', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_estado', verbose_name='Estado del'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desc_fruta', verbose_name='Nombre de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='origen_producto',
            field=models.CharField(max_length=30, verbose_name='Origen del producto'),
        ),
        migrations.AlterField(
            model_name='producto_estado',
            name='desc_estado',
            field=models.CharField(max_length=120, verbose_name='Descripcion estado del producto'),
        ),
        migrations.AlterField(
            model_name='productor_crear_solicitud',
            name='fk_frutas_espacio1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio1', verbose_name='Nombre producto (1)'),
        ),
        migrations.AlterField(
            model_name='productor_crear_solicitud',
            name='fk_frutas_espacio2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio2', verbose_name='Nombre producto (2)'),
        ),
        migrations.AlterField(
            model_name='productor_crear_solicitud',
            name='fk_frutas_espacio3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frutas_espacio3', verbose_name='Nombre producto (3)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='kilos_fruta_espacio1',
            field=models.IntegerField(default=1, verbose_name='Cantidad producto (1)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='kilos_fruta_espacio2',
            field=models.IntegerField(default=1, verbose_name='Cantidad producto (2)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='kilos_fruta_espacio3',
            field=models.IntegerField(default=1, verbose_name='Cantidad producto (3)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_fruta_espacio1',
            field=models.CharField(max_length=500, verbose_name='Nombre producto (1)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_fruta_espacio2',
            field=models.CharField(max_length=500, verbose_name='Nombre producto (2)'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_fruta_espacio3',
            field=models.CharField(max_length=500, verbose_name='Nombre producto (3)'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='cuidad',
            field=models.CharField(max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fec_subasta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de subasta'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='mi_apuesta',
            field=models.IntegerField(verbose_name='Monto de apuesta'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='mi_direccion',
            field=models.CharField(max_length=120, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='tipo_empresa',
            name='desc_tipo_empresa',
            field=models.CharField(max_length=50, verbose_name='Tipo empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Perfil_usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil_usuario', verbose_name='Perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Tipo_usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario', verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=100, verbose_name='Email usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='movil_usuario',
            field=models.CharField(max_length=100, verbose_name='Movil usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fec_venta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de venta'),
        ),
    ]
